[package]
name = "getappid"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[[bin]]
name = "getappid"
path = "src/main.rs"

[dependencies]
wayland-client = "0.31.13"
wayland-protocols = { version = "0.32.11", features = ["client", "staging"] }
wayland-protocols-wlr = { version = "0.3.11", features = ["client"] }
cosmic-protocols = { version = "0.2.0", default-features = false, features = ["client"] }
memmap2 = "0.9"
